services:

    Parallalax\ApiDebugBundle\DataCollector\RequestCollector:
        tags:
            -
                name:     data_collector
                template: '@ParallalaxApiDebug/data_collector/template.html.twig'
                id:       'parallalax.request_collector'
                priority: 300
        public: false

    Parallalax\ApiDebugBundle\Services\RestClientAdapter:
        public: true
        autowire: false
        arguments:
            $request: "@request_stack"
            $env: "%kernel.environment%"
